package ar.edu.um.programacion2.marcosibarra.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SesionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSesionAllPropertiesEquals(Sesion expected, Sesion actual) {
        assertSesionAutoGeneratedPropertiesEquals(expected, actual);
        assertSesionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSesionAllUpdatablePropertiesEquals(Sesion expected, Sesion actual) {
        assertSesionUpdatableFieldsEquals(expected, actual);
        assertSesionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSesionAutoGeneratedPropertiesEquals(Sesion expected, Sesion actual) {
        assertThat(actual)
            .as("Verify Sesion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSesionUpdatableFieldsEquals(Sesion expected, Sesion actual) {
        assertThat(actual)
            .as("Verify Sesion relevant properties")
            .satisfies(a -> assertThat(a.getTokenJWT()).as("check tokenJWT").isEqualTo(expected.getTokenJWT()))
            .satisfies(a -> assertThat(a.getFechaInicio()).as("check fechaInicio").isEqualTo(expected.getFechaInicio()))
            .satisfies(a -> assertThat(a.getFechaExpiracion()).as("check fechaExpiracion").isEqualTo(expected.getFechaExpiracion()))
            .satisfies(a -> assertThat(a.getActiva()).as("check activa").isEqualTo(expected.getActiva()))
            .satisfies(a -> assertThat(a.getUltimoAcceso()).as("check ultimoAcceso").isEqualTo(expected.getUltimoAcceso()))
            .satisfies(a -> assertThat(a.getEventoSeleccionado()).as("check eventoSeleccionado").isEqualTo(expected.getEventoSeleccionado())
            )
            .satisfies(a -> assertThat(a.getEstadoSesion()).as("check estadoSesion").isEqualTo(expected.getEstadoSesion()))
            .satisfies(a ->
                assertThat(a.getAsientosSeleccionados()).as("check asientosSeleccionados").isEqualTo(expected.getAsientosSeleccionados())
            )
            .satisfies(a -> assertThat(a.getCantidadAsientos()).as("check cantidadAsientos").isEqualTo(expected.getCantidadAsientos()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSesionUpdatableRelationshipsEquals(Sesion expected, Sesion actual) {
        // empty method
    }
}
