export enum EstadoSesion {
  LISTA_EVENTOS = 'LISTA_EVENTOS',

  EVENTO_SELECCIONADO = 'EVENTO_SELECCIONADO',

  ASIENTOS_BLOQUEADOS = 'ASIENTOS_BLOQUEADOS',

  DATOS_COMPLETOS = 'DATOS_COMPLETOS',

  VENTA_CONFIRMADA = 'VENTA_CONFIRMADA',

  EXPIRADA = 'EXPIRADA',
}
